---
- name: build vm with Packer
  command: "packer build -var-file {{ item.packer_varfile }} {{ item.packer_template }}"
  args:
    chdir: "/home/vagrant/templates"
  become: false

- name: get qcow name
  find:
    path: "/home/vagrant/templates/output-qemu"
  register: qemu_output

- name: move qcow into libvirt pool
  command: "mv {{ qemu_output.files[0].path }} /var/lib/libvirt/images/"

- name: remove output-qemu
  file:
    path: /home/vagrant/templates/output-qemu
    state: absent

- name: define vm in libvirt
  virt:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'domain-template.xml.j2')}}"
    uri: 'xen:///'

- name: ensure libvmi config dir is present
  file:
    path: /etc/libvmi
    state: directory

- name: check if vm has a rekall profile
  local_action: stat path="{{ role_path }}/files/{{ item.name }}-profile.json"
  register: vm_profile
  become: false

- name: install vm rekall profile
  copy:
    src: "files/{{ item.name }}-profile.json"
    dest: "/etc/libvmi/{{ item.name}}-profile.json"
  when: vm_profile.stat.exists

- name: check if vm has a sysmap
  local_action: stat path="{{ role_path }}/files/{{ item.name }}.map"
  register: sysmap
  become: false

- name: install vm sysmap
  copy:
    src: "files/{{ item.name }}.map"
    dest: "/etc/libvmi/{{ item.name}}.map"
  when: sysmap.stat.exists

- name: install libvmi config entry
  blockinfile:
    path: '/etc/libvmi.conf'
    block: "{{ lookup('file', 'files/'+item.name+'.conf')}}"
    marker: ""
    state: present
    create: yes
