---
- include: packer.yml

- name: install QEMU
  package:
    name: "{{ item }}"
  with_items:
    - qemu-system-x86
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'Ubuntu'

- name: upload templates
  synchronize:
    src: files/templates
    dest: /home/vagrant/

- include: build.yml
  with_items:
    - { name: 'winxp', ram: '512', packer_template: 'windows.json', packer_varfile: 'winxp.json' }

- name: refresh libvirt pool
  command: virsh -c xen:/// pool-refresh default
