---
- name: install unzip for unarchive module
  package:
    name: unzip
  when: ansible_distribution == 'Fedora'

- name: download Packer 1.3.5
  get_url:
    url: 'https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip'
    dest: /tmp/packer.zip

- name: extract Packer
  unarchive:
    src: /tmp/packer.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: remove Packer archive
  file:
    path: /tmp/packer.zip
    state: absent
