Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu1804"

    # build Xen from source
    source = false
    # version of Xen repo to checkout (tag, branch, etc...)
    version = "stable-4.11"
    # install VMI tools
    vmi = true

    config.vm.synced_folder "/home/wenzel/Projets/pyvmidbg", "/vagrant/pyvmidbg",
        :nfs => true,
        :nfs_version => 4

    # config.vm.synced_folder "/home/wenzel/Projets/libvmi-python", "/vagrant/libvmi-python",
    #     :nfs => true,
    #     :nfs_version => 4

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.cpu_mode = 'host-model'
        libvirt.cpu_fallback = 'forbid'
        libvirt.memory = 2048
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true
        libvirt.machine_virtual_size = 40
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "provision/playbook_1.yml"
        ansible.extra_vars = {
            'source': source,
            'version': version,
        }
    end

    config.vm.provision :reload

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "provision/playbook_2.yml"
        ansible.extra_vars = {
            'vmi': vmi,
        }
    end
end
