---
- name: install development tools
  dnf:
    name: '@development-tools'
    state: latest
  when: ansible_distribution == 'Fedora'

- name: clone Xen source code
  git:
    repo: 'git://xenbits.xen.org/xen.git'
    dest: /home/vagrant/xen
    version: "{{ xen_src_version }}"
  become: false

- name: install xen build dependencies with builddep
  command: dnf builddep -y xen kernel
  args:
    warn: false
  when: ansible_distribution == 'Fedora'

- name: install Xen build dependencies
  package:
    name: "{{ item }}"
  with_items:
    - dev86
    - glibc-devel
    - glib2-devel
    - pixman-devel
    - python
    - python-devel
    - python3
    - python3-devel
    - glibc-devel-2.28-27.fc29.i686
  when: ansible_distribution == 'Fedora'

- name: configure Xen
  command: ./configure --enable-systemd
  args:
    chdir: /home/vagrant/xen
  become: false

- name: build Xen
  command: "make -j{{ ansible_processor_vcpus }} dist"
  args:
    chdir: /home/vagrant/xen
  become: false

- name: install Xen
  command: make install
  args:
    chdir: /home/vagrant/xen

- name: update ld configuration
  lineinfile:
    path: /etc/ld.so.conf.d/local.conf
    line: '/usr/local/lib'
    create: yes

- name: rebuild dynamic linker cache
  command: /sbin/ldconfig

- name: update GRUB2
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: update GRUB to boot on Xen kernel by default
  command: grub2-set-default 'Fedora, with Xen hypervisor'
  when: ansible_distribution == 'Fedora'

- name: enable Xen system services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - xen-init-dom0.service
    - xendomains.service
    - xenconsoled.service
    - xenstored.service
