---
- name: install Xen package
  package:
    name: "{{ item }}"
  with_items:
    - xen
  when: ansible_distribution == 'Fedora'

- name: update GRUB to boot on Xen kernel by default
  command: grub2-set-default '2'
  when: ansible_distribution == 'Fedora'
