Vagrant.configure(2) do |config|
    config.vm.box = "generic/fedora29"
    #config.vm.box_version = "32.20200422.0"
    config.vm.define "pyvmidbg"

    # build Xen from source
    xen_src = false
    # version of Xen repo to checkout (tag, branch, etc...)
    xen_src_version = "stable-4.11"
    # install VMI tools
    vmi = true

    synced_folder_hash = {}

    synced_folder_hash.each do |folder, mntpnt|
        remote_folder = mntpnt
        if mntpnt.nil?
            basename = File.basename(folder)
            remote_folder = "/vagrant/#{basename}"
        end
        config.vm.synced_folder folder, remote_folder,
            :nfs => true,
            :nfs_version => 4,
            # speedup NFS with custom options
            :linux__nfs_options => ["rw", "no_subtree_check", "all_squash", "async"]
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.cpu_fallback = 'forbid'
        libvirt.memory = 2048
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "../ansible/playbook_1.yml"
        ansible.extra_vars = {
            'xen_src': xen_src,
            'xen_src_version': xen_src_version,
        }
    end

    config.vm.provision :reload

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "../ansible/playbook_2.yml"
        ansible.extra_vars = {
            'vmi': vmi,
        }
    end
end
