Vagrant.configure(2) do |config|
    config.vm.box = "fedora/29-cloud-base"

    # build Xen from source
    xen_src = false
    # version of Xen repo to checkout (tag, branch, etc...)
    xen_src_version = "stable-4.11"
    # install VMI tools
    vmi = true

    config.vm.synced_folder ".", "/vagrant", disabled: true

    pyvmidbg_path = ""
    config.vm.synced_folder pyvmidbg_path, "/vagrant/pyvmidbg",
        :nfs => true,
        :nfs_version => 4

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.cpu_fallback = 'forbid'
        libvirt.memory = 2048
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "../ansible/playbook_1.yml"
        ansible.extra_vars = {
            'xen_src': xen_src,
            'xen_src_version': xen_src_version,
        }
    end

    config.vm.provision :reload

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "../ansible/playbook_2.yml"
        ansible.extra_vars = {
            'vmi': vmi,
        }
    end
end
