---
- hosts: all
  become: true
  pre_tasks:
    - name: test Xen hypervisor
      slurp:
        src: /sys/hypervisor/type
      register: hypertype
      failed_when: hypertype['content'] | b64decode | trim != "xen"
    - name: refresh ld config to force /usr/local
      command: ldconfig
    - name: get xen version
      shell: xl info | grep xen_version
      register: xen_version
    - name: display xen version
      debug:
        var: xen_version.stdout
    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim
        - wget
        - ipython3
  roles:
    - libvirt
    - libvmi
    - pyvmidbg
    - vm

  post_tasks:
    - name: clear packer cache to free disk space
      file:
        path: "/home/vagrant/templates/packer_cache"
        state: absent
