---
- hosts: all
  become: true
  pre_tasks:
    - name: check for virtualization extensions in cpuinfo
      shell: egrep '(vmx|svm)' /proc/cpuinfo
    - name: gather facts
      setup:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
  roles:
    - xen
    - remote
