---
- hosts: all
  become: true
  pre_tasks:
    - name: check for virtualization extensions in cpuinfo
      shell: egrep '(vmx|svm)' /proc/cpuinfo
    - name: gather facts
      setup:
  roles:
    - xen
    - remote
